# Generated by Django 4.0.4 on 2022-05-22 11:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0005_s_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='s_prof',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_name', models.CharField(max_length=50)),
                ('roll_no', models.CharField(max_length=10)),
                ('dob', models.DateField()),
                ('edu', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('s_no', models.CharField(max_length=12)),
                ('T_add', models.CharField(max_length=100)),
                ('post_code', models.CharField(max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='s_profile',
        ),
    ]
